-- ============================================================
-- GAMERS HUB DATABASE - SUPABASE / POSTGRESQL
-- Converted from the uploaded MySQL / MariaDB schema.
-- Run in Supabase Dashboard -> SQL Editor.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- ENUM TYPES
-- ============================================================

DO $$ BEGIN CREATE TYPE user_status AS ENUM
('active','suspended','banned','deactivated');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE profile_visibility AS ENUM
('public','friends_only','followers_only','private');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE message_permission AS ENUM
('everyone','followers','friends');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE gaming_style AS ENUM
('casual','competitive','both');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE online_status AS ENUM
('online','offline','away','do_not_disturb');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE login_action AS ENUM
('login','logout','security_check');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE game_status AS ENUM
('active','inactive');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE platform_type AS ENUM
('PC','PlayStation','Xbox','Nintendo Switch','Mobile','Steam Deck','Other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE user_game_status AS ENUM
('playing','favorite','played','want_to_play');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE skill_level_type AS ENUM
('beginner','intermediate','advanced','expert');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE post_type AS ENUM
('text','achievement','discussion','question','looking_for_players','review');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE post_visibility AS ENUM
('public','followers','private');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE content_status AS ENUM
('published','hidden','deleted');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE media_type AS ENUM
('image','video');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE reaction_type AS ENUM
('like','love','fire','laugh','sad');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE notification_type AS ENUM
('follow','reaction','comment','share','mention','system',
 'friend_request','friend_accepted','lfg_request','lfg_accepted',
 'lfg_joined','community_invite','security');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE friendship_status AS ENUM
('pending','accepted','rejected','blocked');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE lfg_status AS ENUM
('open','full','closed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE lfg_member_status AS ENUM
('pending','accepted','rejected','left');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE community_visibility AS ENUM
('public','private');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN CREATE TYPE community_role AS ENUM
('member','moderator','admin');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================
-- USERS
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    status user_status NOT NULL DEFAULT 'active',
    email_verified_at TIMESTAMPTZ NULL,
    last_login_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_status ON users(status);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);

-- ============================================================
-- EMAIL VERIFICATION TOKENS
-- ============================================================

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    token CHAR(7) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_verification_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_verification_tokens_user
ON email_verification_tokens(user_id);

CREATE INDEX IF NOT EXISTS idx_verification_tokens_expires
ON email_verification_tokens(expires_at);

-- ============================================================
-- USER PROFILES
-- ============================================================

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id BIGINT PRIMARY KEY,
    display_name VARCHAR(50) NOT NULL,
    bio VARCHAR(500) NULL,

    social_discord VARCHAR(500) NULL,
    social_tiktok VARCHAR(500) NULL,
    social_facebook VARCHAR(500) NULL,
    social_twitch VARCHAR(500) NULL,
    social_kick VARCHAR(500) NULL,
    social_github VARCHAR(500) NULL,
    social_spotify VARCHAR(500) NULL,
    social_youtube VARCHAR(500) NULL,
    social_apple_music VARCHAR(500) NULL,
    social_steam VARCHAR(500) NULL,
    social_x VARCHAR(500) NULL,

    profile_visibility profile_visibility NOT NULL DEFAULT 'public',
    who_can_message message_permission NOT NULL DEFAULT 'everyone',

    avatar_url VARCHAR(500) NULL,
    cover_url VARCHAR(500) NULL,
    location VARCHAR(100) NULL,

    gaming_style gaming_style NOT NULL DEFAULT 'both',
    preferred_voice_chat BOOLEAN NOT NULL DEFAULT TRUE,

    email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    push_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    social_notifications BOOLEAN NOT NULL DEFAULT TRUE,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,

    online_status online_status NOT NULL DEFAULT 'offline',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT unique_display_name UNIQUE (display_name),
    CONSTRAINT fk_profile_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- SESSIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS sessions (
    id CHAR(64) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent TEXT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_sessions_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

-- ============================================================
-- USER LOGIN HISTORY
-- ============================================================

CREATE TABLE IF NOT EXISTS user_login_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    session_id CHAR(64) NULL,
    device_name VARCHAR(120) NOT NULL,
    ip_hash CHAR(64) NOT NULL,
    location VARCHAR(120) NULL,
    user_agent TEXT NULL,
    action login_action NOT NULL DEFAULT 'login',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_login_history_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_login_history_session
        FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_login_history_user
ON user_login_history(user_id);

CREATE INDEX IF NOT EXISTS idx_login_history_session
ON user_login_history(session_id);

CREATE INDEX IF NOT EXISTS idx_login_history_created_at
ON user_login_history(created_at);

-- ============================================================
-- GAMES
-- ============================================================

CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    slug VARCHAR(150) NOT NULL UNIQUE,
    description TEXT NULL,
    cover_url VARCHAR(500) NULL,
    icon_url VARCHAR(500) NULL,
    developer VARCHAR(150) NULL,
    publisher VARCHAR(150) NULL,
    release_date DATE NULL,
    status game_status NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_games_name ON games(name);
CREATE INDEX IF NOT EXISTS idx_games_status ON games(status);

-- ============================================================
-- GAME PLATFORMS
-- ============================================================

CREATE TABLE IF NOT EXISTS game_platforms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    platform platform_type NOT NULL,

    CONSTRAINT fk_game_platform_game
        FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    CONSTRAINT unique_game_platform UNIQUE (game_id, platform)
);

-- ============================================================
-- USER GAMES
-- ============================================================

CREATE TABLE IF NOT EXISTS user_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    status user_game_status NOT NULL DEFAULT 'playing',
    hours_played NUMERIC(10,2) NULL,
    skill_level skill_level_type NULL,
    rank_name VARCHAR(100) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_user_games_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_games_game
        FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,
    CONSTRAINT unique_user_game UNIQUE (user_id, game_id)
);

CREATE INDEX IF NOT EXISTS idx_user_games_game ON user_games(game_id);
CREATE INDEX IF NOT EXISTS idx_user_games_user ON user_games(user_id);

-- ============================================================
-- USER ONBOARDING PREFERENCES
-- ============================================================

CREATE TABLE IF NOT EXISTS user_gamer_types (
    user_id BIGINT NOT NULL,
    gamer_type VARCHAR(40) NOT NULL,
    PRIMARY KEY (user_id, gamer_type),
    CONSTRAINT fk_user_gamer_types_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_platforms (
    user_id BIGINT NOT NULL,
    platform VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, platform),
    CONSTRAINT fk_user_platforms_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_goals (
    user_id BIGINT NOT NULL,
    goal VARCHAR(60) NOT NULL,
    PRIMARY KEY (user_id, goal),
    CONSTRAINT fk_user_goals_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_content_preferences (
    user_id BIGINT NOT NULL,
    content_type VARCHAR(60) NOT NULL,
    PRIMARY KEY (user_id, content_type),
    CONSTRAINT fk_user_content_preferences_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- FOLLOWERS
-- ============================================================

CREATE TABLE IF NOT EXISTS followers (
    follower_id BIGINT NOT NULL,
    following_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (follower_id, following_id),

    CONSTRAINT fk_followers_follower
        FOREIGN KEY (follower_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_followers_following
        FOREIGN KEY (following_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_followers_not_self CHECK (follower_id <> following_id)
);

CREATE INDEX IF NOT EXISTS idx_followers_following
ON followers(following_id);

CREATE INDEX IF NOT EXISTS idx_followers_follower
ON followers(follower_id);

-- ============================================================
-- FRIENDSHIPS
-- Added for the Friends page.
-- ============================================================

CREATE TABLE IF NOT EXISTS friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    status friendship_status NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    accepted_at TIMESTAMPTZ NULL,

    CONSTRAINT fk_friendships_requester
        FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_friendships_receiver
        FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_friendships_not_self CHECK (requester_id <> receiver_id),
    CONSTRAINT uq_friend_request UNIQUE (requester_id, receiver_id)
);

CREATE INDEX IF NOT EXISTS idx_friendships_requester
ON friendships(requester_id, status);

CREATE INDEX IF NOT EXISTS idx_friendships_receiver
ON friendships(receiver_id, status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_friendships_pair
ON friendships (
    LEAST(requester_id, receiver_id),
    GREATEST(requester_id, receiver_id)
);

-- ============================================================
-- MESSAGING
-- ============================================================

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_group BOOLEAN NOT NULL DEFAULT FALSE,
    title VARCHAR(120) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_conversations_updated_at
ON conversations(updated_at);

CREATE TABLE IF NOT EXISTS conversation_participants (
    conversation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    last_read_message_id BIGINT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (conversation_id, user_id),

    CONSTRAINT fk_conversation_participants_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES conversations(id) ON DELETE CASCADE,

    CONSTRAINT fk_conversation_participants_user
        FOREIGN KEY (user_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_conversation_participants_user
ON conversation_participants(user_id);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    body TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_messages_conversation
        FOREIGN KEY (conversation_id)
        REFERENCES conversations(id) ON DELETE CASCADE,

    CONSTRAINT fk_messages_sender
        FOREIGN KEY (sender_id)
        REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation_created
ON messages(conversation_id, created_at, id);

CREATE INDEX IF NOT EXISTS idx_messages_sender
ON messages(sender_id);

-- ============================================================
-- POSTS
-- ============================================================

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    game_id BIGINT NULL,
    post_type post_type NOT NULL DEFAULT 'text',
    content TEXT NOT NULL,
    visibility post_visibility NOT NULL DEFAULT 'public',
    status content_status NOT NULL DEFAULT 'published',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_posts_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT fk_posts_game
        FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_posts_user_created
ON posts(user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_posts_game_created
ON posts(game_id, created_at);

CREATE INDEX IF NOT EXISTS idx_posts_created
ON posts(created_at);

CREATE INDEX IF NOT EXISTS idx_posts_status
ON posts(status);

-- ============================================================
-- POST MEDIA
-- ============================================================

CREATE TABLE IF NOT EXISTS post_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    media_type media_type NOT NULL,
    media_url VARCHAR(1000) NOT NULL,
    thumbnail_url VARCHAR(1000) NULL,
    file_size BIGINT NULL,
    width INTEGER NULL,
    height INTEGER NULL,
    duration_seconds INTEGER NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_post_media_post
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,

    CONSTRAINT chk_post_media_file_size
        CHECK (file_size IS NULL OR file_size >= 0),

    CONSTRAINT chk_post_media_dimensions
        CHECK (
            (width IS NULL OR width >= 0)
            AND (height IS NULL OR height >= 0)
        ),

    CONSTRAINT chk_post_media_duration
        CHECK (duration_seconds IS NULL OR duration_seconds >= 0)
);

CREATE INDEX IF NOT EXISTS idx_post_media_post
ON post_media(post_id);

-- ============================================================
-- POST REACTIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS post_reactions (
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    reaction_type reaction_type NOT NULL DEFAULT 'like',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (post_id, user_id),

    CONSTRAINT fk_reactions_post
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,

    CONSTRAINT fk_reactions_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_reactions_user
ON post_reactions(user_id);

-- ============================================================
-- COMMENTS
-- ============================================================

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    content TEXT NOT NULL,
    status content_status NOT NULL DEFAULT 'published',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_comments_post
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,

    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT fk_comments_parent
        FOREIGN KEY (parent_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_comments_post
ON comments(post_id, created_at);

CREATE INDEX IF NOT EXISTS idx_comments_user
ON comments(user_id);

CREATE INDEX IF NOT EXISTS idx_comments_parent
ON comments(parent_id);

-- ============================================================
-- POST SHARES
-- ============================================================

CREATE TABLE IF NOT EXISTS post_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_shares_post
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,

    CONSTRAINT fk_shares_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_shares_post ON post_shares(post_id);
CREATE INDEX IF NOT EXISTS idx_shares_user ON post_shares(user_id);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    actor_id BIGINT NULL,
    type notification_type NOT NULL,
    post_id BIGINT NULL,
    message VARCHAR(500) NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT fk_notifications_actor
        FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL,

    CONSTRAINT fk_notifications_post
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_read
ON notifications(user_id, is_read, created_at);

-- ============================================================
-- LFG POSTS
-- ============================================================

CREATE TABLE IF NOT EXISTS lfg_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL UNIQUE,
    game_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    platform VARCHAR(50) NULL,
    players_needed INTEGER NOT NULL DEFAULT 1,
    players_joined INTEGER NOT NULL DEFAULT 0,
    rank_required VARCHAR(100) NULL,
    voice_required BOOLEAN NOT NULL DEFAULT FALSE,
    region VARCHAR(100) NULL,
    status lfg_status NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_lfg_post
        FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,

    CONSTRAINT fk_lfg_game
        FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE,

    CONSTRAINT fk_lfg_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,

    CONSTRAINT chk_lfg_players_needed CHECK (players_needed >= 1),
    CONSTRAINT chk_lfg_players_joined CHECK (players_joined >= 0)
);

CREATE INDEX IF NOT EXISTS idx_lfg_game_status
ON lfg_posts(game_id, status);

CREATE INDEX IF NOT EXISTS idx_lfg_user
ON lfg_posts(user_id);

-- ============================================================
-- LFG MEMBERS
-- ============================================================

CREATE TABLE IF NOT EXISTS lfg_members (
    lfg_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status lfg_member_status NOT NULL DEFAULT 'pending',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (lfg_id, user_id),

    CONSTRAINT fk_lfg_members_lfg
        FOREIGN KEY (lfg_id) REFERENCES lfg_posts(id) ON DELETE CASCADE,

    CONSTRAINT fk_lfg_members_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- ============================================================
-- COMMUNITIES
-- ============================================================

CREATE TABLE IF NOT EXISTS communities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL UNIQUE,
    description TEXT NULL,
    avatar_url VARCHAR(500) NULL,
    cover_url VARCHAR(500) NULL,
    visibility community_visibility NOT NULL DEFAULT 'public',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_communities_owner
        FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_communities_name
ON communities(name);

-- ============================================================
-- COMMUNITY MEMBERS
-- ============================================================

CREATE TABLE IF NOT EXISTS community_members (
    community_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role community_role NOT NULL DEFAULT 'member',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (community_id, user_id),

    CONSTRAINT fk_community_members_community
        FOREIGN KEY (community_id) REFERENCES communities(id) ON DELETE CASCADE,

    CONSTRAINT fk_community_members_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_community_members_user
ON community_members(user_id);

-- ============================================================
-- SAMPLE GAMES
-- ============================================================

INSERT INTO games (name, slug, description, developer, publisher)
VALUES
('Valorant', 'valorant',
 'Free-to-play competitive tactical shooter.',
 'Riot Games', 'Riot Games'),

('Counter-Strike 2', 'counter-strike-2',
 'Competitive multiplayer tactical first-person shooter.',
 'Valve', 'Valve'),

('Minecraft', 'minecraft',
 'Sandbox game focused on exploration and creation.',
 'Mojang Studios', 'Mojang Studios'),

('Grand Theft Auto V', 'grand-theft-auto-v',
 'Open-world action-adventure game.',
 'Rockstar North', 'Rockstar Games'),

('Dota 2', 'dota-2',
 'Competitive multiplayer online battle arena.',
 'Valve', 'Valve'),

('League of Legends', 'league-of-legends',
 'Competitive multiplayer online battle arena.',
 'Riot Games', 'Riot Games'),

('Call of Duty', 'call-of-duty',
 'First-person shooter franchise.',
 'Activision', 'Activision'),

('Euro Truck Simulator 2', 'euro-truck-simulator-2',
 'Truck driving simulation game.',
 'SCS Software', 'SCS Software')

ON CONFLICT (slug) DO NOTHING;

-- ============================================================
-- GAME PLATFORMS
-- ============================================================

INSERT INTO game_platforms (game_id, platform)
SELECT id, 'PC'::platform_type
FROM games
WHERE slug IN (
    'valorant',
    'counter-strike-2',
    'minecraft',
    'grand-theft-auto-v',
    'dota-2',
    'league-of-legends',
    'call-of-duty',
    'euro-truck-simulator-2'
)
ON CONFLICT (game_id, platform) DO NOTHING;

-- ============================================================
-- UPDATED_AT TRIGGER
-- Replaces MySQL ON UPDATE CURRENT_TIMESTAMP.
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_user_profiles_updated_at ON user_profiles;
CREATE TRIGGER trg_user_profiles_updated_at
BEFORE UPDATE ON user_profiles
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_user_games_updated_at ON user_games;
CREATE TRIGGER trg_user_games_updated_at
BEFORE UPDATE ON user_games
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_conversations_updated_at ON conversations;
CREATE TRIGGER trg_conversations_updated_at
BEFORE UPDATE ON conversations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_posts_updated_at ON posts;
CREATE TRIGGER trg_posts_updated_at
BEFORE UPDATE ON posts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS trg_comments_updated_at ON comments;
CREATE TRIGGER trg_comments_updated_at
BEFORE UPDATE ON comments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- END
-- ============================================================
